# =====================================================================================================================
# Spring Boot Profile Group Config
# =====================================================================================================================
spring:
  profiles:
    active: local
    group:
      test:
        - common
        - test
      local:
        - common
        - local
      prod:
        - common
        - prod


---
# =====================================================================================================================
# Spring Boot Common Config
# =====================================================================================================================

spring:
  config:
    activate:
      on-profile: common
  banner:
    location: classpath:banner.txt
  output:
    ansi:
      enabled: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    # multipart
    multipart:
      max-file-size: 100MB
      max-request-size: 150MB

  # messages
  messages:
    basename: messages.messages, messages.common
    encoding: UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      # 세션 타임아웃: 1시간 (3600초)
      timeout: 3600
      tracking-modes: cookie
  # graceful 종료 활성
  shutdown: graceful


# =====================================================================================================================
# project
# =====================================================================================================================

project:
  name-kor: CMS
  name: CMS
  service: CMD_ADMIN
  alias: ${project.service}
  # project.system
  system:
    # 접근 허용  url prefix
    admin-permit-all-url:
      - /login
      - /logout
    # 접근 허용, 인증필요 url
    admin-permit-auth-url:
      - /main
      - /common/file/.*
    # 파일 업로드 경로
    upload-path:
    admin-site-url: http://localhost:8080

  # project.http
  http:
    # connection pool 설정, Second 단위
    max-idle-connections: 5
    keep-alive-duration: 60
