# =====================================================================================================================
# Spring Boot Profile Group Config
# =====================================================================================================================

spring:
  profiles:
    active:
      - local

# =====================================================================================================================
# project
# =====================================================================================================================

project:
  name-kor: CMS???
  name: CMS
  service: CMD_ADMIN
  alias: ${project.service}-admin

  # project.system
  system:
    # ?? ?? url prefix (?? path ??) - ??? ? ?? ?? ?? ??
    admin-permit-all-url:
      - /login
      - /logout
    # ?? ?? ?? url - ??? ??? ??? ??? ??? ?? ??
    admin-permit-auth-url:
      - /main
      - /common/file/.*
    # /api ? ???? url - ??? ? ?? ??
    upload-path:

  # project.http
  http:
    # connection pool ??, Second ??
    max-idle-connections: 5
    keep-alive-duration: 60
